[build]
base = "dsa-platform-web"
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/api/*"
to = "https://dsa-platform-production-64f6.up.railway.app/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin-allow-popups"
Cross-Origin-Embedder-Policy = "unsafe-none"
